esphome:
  name: lilygo
  platformio_options:
    # Unless noted otherwise, based on https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/1eb6119fc31fcff7a6bafecb09f4225313859fc5/examples/demo/platformio.ini#L37
    upload_speed: 921600
    monitor_speed: 115200
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
    board_build.arduino.memory_type: qspi_opi
    board_build.flash_size: 16MB
    board_build.flash_mode: qio
    board_build.flash_type: qspi
    board_build.psram_type: opi
    board_build.memory_type: qspi_opi
    board_build.boot_freq: 80m
    platform_packages:
      - "toolchain-riscv32-esp @8.4.0+2021r2-patch5"
    build_flags:  # the first three defines are required for the screen library to function.
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_RUNNING_CORE=0"  # TODO: this conflicts with the value from platformio's idedata, spewing a lot of warnings during the build.
      - "-DARDUINO_EVENT_RUNNING_CORE=0"  # and this too
      # In addition to lilygo's settings:
      # To enable reading logs over USB until `hardware_uart: USB_CDC` support
      # is added to `logger:`, as detailed in <https://github.com/esphome/feature-requests/issues/1906>:
      - "-DARDUINO_USB_MODE=1"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1

  framework:
    type: arduino
    # Just like in <https://community.home-assistant.io/t/enable-usb-cdc-to-log-hello-world-to-esp32-s3-dev-board-for-esphome/463164/10>
    # I had problems with newer versions; the following combination happens to work, so using it for now.
    version: 2.0.3
    platform_version: 5.1.1

logger:
  level: VERBOSE
  # hardware_uart: USB_CDC  # see note about <https://github.com/esphome/feature-requests/issues/1906> above


# Enable Home Assistant API
api:
  encryption:
    key: "your_enc_key"

ota:
  password: "your_enc_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "E-Paper Fallback Hotspot"
    password: "esphome123"

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO21 #was GPIO39 on the previous board
      inverted: true
    name: "Button 1"
    on_press:
      - logger.log: PhysButton Pressed

external_components:
  source:
    type: local
    path: components/
  components: ["t547", "lilygo_t5_47_battery"]

captive_portal:

sensor:
  - platform: homeassistant
    id: battery_voltage
    entity_id: sensor.battery_voltage

  - platform: lilygo_t5_47_battery
    id: t547_voltage
    voltage:
      name: "Battery Voltage"

  - platform: template
    name: "t547 Battery Percentage"
    id: t547_battery_percentage
    lambda: |-
      // tweak values in mapping for calibration
      // 4.1 = max voltage
      // 3.3 = min voltage
      float y = (id(t547_voltage).voltage->state - 3.3) * 100.0 / (4.1 - 3.3);
      if (y < 100.0) { return y; } else { return 100.0; };

  - platform: homeassistant
    id: out_temp
    entity_id: sensor.fineoffset_whx080_0_64_temperature

  - platform: homeassistant
    id: out_humidity
    entity_id: sensor.fineoffset_whx080_0_64_humidity

  - platform: homeassistant
    id: wind_speed
    entity_id: sensor.fineoffset_wind_average_mph

  - platform: homeassistant
    id: wind_speed_gust
    entity_id: sensor.fineoffset_wind_gust_average_mph

#  - platform: homeassistant
#    id: daily_rain
#    entity_id: sensor.daily_rain

#  - platform: homeassistant
#    id: air_pressure
#    entity_id: sensor.air_pressure

  - platform: homeassistant
    id: temp_h1
    entity_id: sensor.temperature_forecast_h1
  
  - platform: homeassistant
    id: temp_h2
    entity_id: sensor.temperature_forecast_h2
  
  - platform: homeassistant
    id: temp_h3
    entity_id: sensor.temperature_forecast_h3

  - platform: homeassistant
    id: temp_h4
    entity_id: sensor.temperature_forecast_h4

  - platform: homeassistant
    id: temp_h5
    entity_id: sensor.temperature_forecast_h5

  - platform: homeassistant
    id: temp_d1
    entity_id: sensor.temperature_forecast_d1
  
  - platform: homeassistant
    id: temp_d2
    entity_id: sensor.temperature_forecast_d2
  
  - platform: homeassistant
    id: temp_d3
    entity_id: sensor.temperature_forecast_d3

  - platform: homeassistant
    id: temp_d4
    entity_id: sensor.temperature_forecast_d4

  - platform: homeassistant
    id: temp_d5
    entity_id: sensor.temperature_forecast_d5

text_sensor:
  - platform: homeassistant
    id: wind_dir
    entity_id: sensor.cardinal_wind_dir

  - platform: homeassistant
    id: weather_now
    entity_id: sensor.weathercurrent
  
  - platform: homeassistant
    id: weather_h1
    entity_id: sensor.weather_forecast_h1
  
  - platform: homeassistant
    id: weather_h2
    entity_id: sensor.weather_forecast_h2
  
  - platform: homeassistant
    id: weather_h3
    entity_id: sensor.weather_forecast_h3

  - platform: homeassistant
    id: weather_h4
    entity_id: sensor.weather_forecast_h4
  
  - platform: homeassistant
    id: weather_h5
    entity_id: sensor.weather_forecast_h5

  - platform: homeassistant
    id: weather_d1
    entity_id: sensor.weather_forecast_d1
  
  - platform: homeassistant
    id: weather_d2
    entity_id: sensor.weather_forecast_d2
  
  - platform: homeassistant
    id: weather_d3
    entity_id: sensor.weather_forecast_d3

  - platform: homeassistant
    id: weather_d4
    entity_id: sensor.weather_forecast_d4

  - platform: homeassistant
    id: weather_d5
    entity_id: sensor.weather_forecast_d5

button:
  - platform: restart
    name: "Dashboard - Restart"

font:
  - file: "gfonts://Inter@900"
    id: big
    size: 120
  - file: "gfonts://Inter@900"
    id: medium
    size: 60
  - file: "gfonts://Inter@700"
    id: small
    size: 30
  - file: "gfonts://Inter@700"
    id: tiny
    size: 24
  - file: "fonts/OCRAEXT.ttf"
    id: fontocra_24
    size: 24

  # Include Material Design Icons font
  # Thanks to https://community.home-assistant.io/t/display-materialdesign-icons-on-esphome-attached-to-screen/199790/16
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_large
    size: 200
    glyphs: &mdi-weather-glyphs
      - "\U000F0590" # mdi-weather-cloudy
      - "\U000F0F2F" # mdi-weather-cloudy-alert
      - "\U000F0E6E" # mdi-weather-cloudy-arrow-right
      - "\U000F0591" # mdi-weather-fog
      - "\U000F0592" # mdi-weather-hail
      - "\U000F0F30" # mdi-weather-hazy
      - "\U000F0898" # mdi-weather-hurricane
      - "\U000F0593" # mdi-weather-lightning
      - "\U000F067E" # mdi-weather-lightning-rainy
      - "\U000F0594" # mdi-weather-clear-night
      - "\U000F0F31" # mdi-weather-night-partly-cloudy
      - "\U000F0595" # mdi-weather-partly-cloudy
      - "\U000F0F32" # mdi-weather-partly-lightning
      - "\U000F0F33" # mdi-weather-partly-rainy
      - "\U000F0F34" # mdi-weather-partly-snowy
      - "\U000F0F35" # mdi-weather-partly-snowy-rainy
      - "\U000F0596" # mdi-weather-pouring
      - "\U000F0597" # mdi-weather-rainy
      - "\U000F0598" # mdi-weather-snowy
      - "\U000F0F36" # mdi-weather-snowy-heavy
      - "\U000F067F" # mdi-weather-snowy-rainy
      - "\U000F0599" # mdi-weather-sunny
      - "\U000F0F37" # mdi-weather-sunny-alert
      - "\U000F14E4" # mdi-weather-sunny-off
      - "\U000F059A" # mdi-weather-sunset
      - "\U000F059B" # mdi-weather-sunset-down
      - "\U000F059C" # mdi-weather-sunset-up
      - "\U000F0F38" # mdi-weather-tornado
      - "\U000F059D" # mdi-weather-windy
      - "\U000F059E" # mdi-weather-windy-variant
  - file: 'fonts/materialdesignicons-webfont.ttf'
    id: font_mdi_medium
    size: 40
    glyphs: *mdi-weather-glyphs


#Make Temp Graph
graph:
    - id: temp_graph
      duration: 12h
      width: 300
      height: 50
      border: False
      traces:
        - sensor: out_temp
          line_thickness: 1
#Display Setup

display:
  - platform: t547
    # rotation: 180
    update_interval: 60s

    lambda: |-
      // Map weather states to MDI characters.
      std::map<std::string, std::string> weather_icon_map
        {
          {"cloudy", "\U000F0590"},
          {"cloudy-alert", "\U000F0F2F"},
          {"cloudy-arrow-right", "\U000F0E6E"},
          {"fog", "\U000F0591"},
          {"hail", "\U000F0592"},
          {"hazy", "\U000F0F30"},
          {"hurricane", "\U000F0898"},
          {"lightning", "\U000F0593"},
          {"lightning-rainy", "\U000F067E"},
          {"clear-night", "\U000F0594"},
          {"night-partly-cloudy", "U000F0F31"},
          {"partlycloudy", "\U000F0595"},
          {"partly-lightning", "\U000F0F32"},
          {"partly-rainy", "\U000F0F33"},
          {"partly-snowy", "\U000F0F34"},
          {"partly-snowy-rainy", "\U000F0F35"},
          {"pouring", "\U000F0596"},
          {"rainy", "\U000F0597"},
          {"snowy", "\U000F0598"},
          {"snowy-heavy", "\U000F0F36"},
          {"snowy-rainy", "\U000F067F"},
          {"sunny", "\U000F0599"},
          {"sunny-alert", "\U000F0F37"},
          {"sunny-off", "\U000F14E4"},
          {"sunset", "\U000F059A"},
          {"sunset-down", "\U000F059B"},
          {"sunset-up", "\U000F059C"},
          {"tornado", "\U000F0F38"},
          {"windy", "\U000F059D"},
          {"windy-variant", "\U000F059E"},
        };

      // Forecast Boxes
      it.rectangle(550,200,80,80);
      it.rectangle(550,200,160,80);
      it.rectangle(550,200,240,80);
      it.rectangle(550,200,320,80);
      it.rectangle(550,200,400,80);
      it.rectangle(550,340,80,80);
      it.rectangle(550,340,160,80);
      it.rectangle(550,340,240,80);
      it.rectangle(550,340,320,80);
      it.rectangle(550,340,400,80);
      //Date and Time
      it.strftime(480, 10, id(small), TextAlign::CENTER_HORIZONTAL, "%A %B %d, %Y", id(homeassistant_time).now());
      it.strftime(480, 30, id(big), TextAlign::CENTER_HORIZONTAL, "%H:%M", id(homeassistant_time).now());
      //Current Weather
      it.printf(400, 160, id(tiny), TextAlign::CENTER_HORIZONTAL, "Currently: %s", id(weather_now).state.c_str());
      it.printf(400, 180, id(font_mdi_large), TextAlign::CENTER_HORIZONTAL, "%s", weather_icon_map[id(weather_now).state.c_str()].c_str());
      //it.printf(400, 340, id(small), TextAlign::CENTER_HORIZONTAL, "%s", id(weather_now).state.c_str());
      it.printf(400, 360, id(medium), TextAlign::CENTER_HORIZONTAL, "%.1f°", id(out_temp).state);
      //Hourly Forecast
      it.printf(6700,170, id(tiny), TextAlign::CENTER_HORIZONTAL, "Hourly Forecast");
      it.printf(590,210,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_h1).state.c_str()].c_str());
      it.printf(670,210,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_h2).state.c_str()].c_str());
      it.printf(750,210,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_h3).state.c_str()].c_str());
      it.printf(830,210,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_h4).state.c_str()].c_str());
      it.printf(910,210,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_h5).state.c_str()].c_str());
      it.printf(590,250,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_h1).state);
      it.printf(670,250,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_h2).state);
      it.printf(750,250,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_h3).state);
      it.printf(830,250,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_h4).state);
      it.printf(910,250,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_h5).state);
      //Daily Forecast
      it.printf(670,310, id(tiny), TextAlign::CENTER_HORIZONTAL, "Daily Forecast");
      it.printf(590,350,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_d1).state.c_str()].c_str());
      it.printf(670,350,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_d2).state.c_str()].c_str());
      it.printf(750,350,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_d1).state.c_str()].c_str());
      it.printf(830,350,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_d4).state.c_str()].c_str());
      it.printf(910,350,id(font_mdi_medium),TextAlign::CENTER_HORIZONTAL,"%s",weather_icon_map[id(weather_d5).state.c_str()].c_str());
      it.printf(590,390,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_d1).state);
      it.printf(670,390,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_d2).state);
      it.printf(750,390,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_d3).state);
      it.printf(830,390,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_d4).state);
      it.printf(910,390,id(tiny),TextAlign::CENTER_HORIZONTAL, "%.0f°", id(temp_d5).state);
      //Outdoor Data
      it.printf(20, 240, id(tiny), "Rain Today: %.1f°", id(out_temp).state); // change (out_temp) to (daily_rain) for the rainfall sensor once we find it 
      it.printf(20, 270, id(tiny), "Humidity: %.1f%%", id(out_humidity).state);
      it.printf(20, 300, id(tiny), "Wind Speed: %.1f°", id(wind_speed).state);
      it.printf(20, 330, id(tiny), "Wind Speed: %.1f%%", id(wind_speed_gust).state);
      it.printf(20, 360, id(tiny), "Wind Direction: %.1f°", id(wind_dir).state);
      //it.printf(20, 390, id(tiny), "Air Pressure: %.1f°", id(air_pressure).state); // enable once air pressure sensor is active
      //Temp Graph
      it.graph(500, 200, id(temp_graph));   
      it.printf(60, 510, id(fontocra_24), TextAlign::TOP_LEFT, "Battery: %.1f%%", id(t547_battery_percentage).state);
      it.printf(320, 510, id(fontocra_24), TextAlign::TOP_LEFT, "Voltage: %.2fV", id(battery_voltage).state);